version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: kinopoisk123
      POSTGRES_DB: kino-poisk
      POSTGRES_HOST: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "1337:5432" # Исправлен порт, чтобы он совпадал с портом в контейнере

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kinopoisk123
      POSTGRES_DB: kino-poisk
      POSTGRES_HOST: db
    volumes:
      - ./templates:/root/templates # Поправлен путь к шаблонам
      - ./static:/root/static # Поправлен путь к статическим файлам
      - ./kinopoisk/controllers:/root/controllers # Поправлен путь к контроллерам
      - ./kinopoisk/database:/root/database # Поправлен путь к базе данных
    depends_on:
      db:
        condition: service_healthy
